### ISSUE TITLE
Fixed header and drawer for width between 850px and 1024px

### ISSUE THREAD

**Issue by jeanmatthieud** [google/material-design-lite#1245]
MDL version: 1.0.1
Browser: Chrome
Browser version: 44
Operating system: Windows
Operating system version: 7
URL : Codepen of the offical doc "Fixed header and drawer" (http://codepen.io/anon/pen/GJwQJa)

What steps will reproduce the problem:
1. Reduce the width of the browser between 850px and 1024px

What is the expected result?
The drawer is displayed or the hamburger icon is displayed
and the header bar is "full width"

What happens instead of that?
The drawer is not displayed and the header bar is splitted in two parts

**Comment by surma** [comment]
This has been fixed in 1.0.2. If you update your codepen to 1.0.2, it works :)

**Comment by jeanmatthieud** [comment]
There is still an issue with the 1.0.2 :
When the width of the browser window is below 1024, and a title is present in the header bar, the burger icon is displayed over the title.
The codepen has been updated : http://codepen.io/anon/pen/GJwQJa
