### ISSUE TITLE
Inconsistencies in documentation regarding mdl-layout-icon

### ISSUE THREAD

**Issue by SeanBannister** [google/material-design-lite#1294]
In the [layout documentation](http://www.getmdl.io/components/index.html#layout-section) the ```mdl-layout-icon``` isn't used in any of the codepen examples. But it is used in the examples under the "Basic Use" section.

When you read the "Basic Use" section it introduces ```mdl-layout-icon``` in point "3" where it states 
> Inside the header, add a \<div\> to produce the menu icon, and include the MDL class as indicated.

But adding this div doesn't "produce the menu icon" [here's a codepen](http://codepen.io/anon/pen/YXBzZz) with the example code.

I'm wondering if this class needs to exist? The examples that use it work fine without it and none of the codepen examples use it.

**Comment by sgomes** [comment]
That documentation is wrong, thanks for pointing out, @SeanBannister. That class simply helps with adding an application icon, should you want to. It doesn't affect the menu icon, other than if there is both an application icon and a menu icon (due to your chosen layout options), the menu icon will get displayed, out of the two.

I'll cook up a PR to fix the docs.

**Comment by sgomes** [comment]
This should be fixed with #1327!

**Comment by SeanBannister** [comment]
@sgomes Maybe the example code needs updating because I'm still not 100% how this works :)

The example currently looks like this:
```
<div class="mdl-layout-icon"></div>
```

Should this have an ```<img>``` inside to make more sense to developers?

**Comment by sgomes** [comment]
@SeanBannister Just added that in, thanks for the suggestion!

**Comment by clemf** [comment]
I'm confused, this is marked as closed but the text is still in the documentation.

**Comment by sgomes** [comment]
@clemf Which particular text are you referring to? The description for `mdl-layout-icon` has been updated to read
> Used for adding an application icon. Gets concealed by menu icon if both are visible.

**Comment by clemf** [comment]
@sgomes Ok, I didn't see that. I was confused because I'm using the menu component. Thanks for the response.
