### ISSUE TITLE
Textfield label overlaps if input has placeholder

### ISSUE THREAD

**Issue by Garbee** [google/material-design-lite#243]
The textfield (at least with a single-line) doesn't look right at all if you give the input a placeholder.

For example:
```html
<div class="mdl-textfield mdl-js-textfield">
            <input class="mdl-textfield__input" type="email" id="email" name="email" placeholder="you@example.com" required>
            <label class="mdl-textfield__label" for="email">Email:</label>
        </div>
```

This provides a display where the placeholder overlaps the label making both unreadable. Placeholders are pretty common when you are expecting a specific format within a text area to show a user how to enter something. While pattern matching and such do work, placeholders are effective in portraying what is requested ahead of time.

Anything we can do here considering the [spec on Text Fields](http://www.google.com/design/spec/components/text-fields.html) makes no mention of placeholders?

**Comment by RootCrashed** [comment]
same issue for me

**Comment by RootCrashed** [comment]
![2016-01-28_182032](https://cloud.githubusercontent.com/assets/10883393/12644853/e8e57078-c5eb-11e5-8592-706fb2d5598b.png)

**Comment by sgomes** [comment]
@RootCrashed This specific bug has already been fixed, so if you're seeing this in the latest version (1.0.6), please try to reproduce it in a codepen so that we can analyse it, and open a new bug if needed. Thanks!

**Comment by Futourism** [comment]
Still reproducible in v.1.1.1 with e.g. this code:

``` 
<div class="mdl-textfield mdl-js-textfield search-textfield">
<input class="mdl-textfield__input" id="txtSearch" type="text">
<label class="mdl-textfield__label" for="txtSearch">Search for ...</label>
</div>
```

**Comment by surma** [comment]
Confirmed: https://codepen.io/surma/pen/JXdEqe

**Comment by sgomes** [comment]
I can definitely see the issue with your codepen, Surma, but I don't understand what the use-case is for defining both a label and a placeholder on the input? What would be the expected behaviour?

**Comment by macx** [comment]
@sgomes I have the same in a actual project. For the floating labels I'm using the title (e.g. "Date of Publishing") and for the Placeholder I'm using an example date to show users the right formatting.

**Comment by RootCrashed** [comment]
i am using label inplace of placeholder

On 4 March 2016 at 19:28, David Maciejewski <notifications@github.com>
wrote:

> @sgomes <https://github.com/sgomes> I have the same in a actual project.
> For the floating labels I'm using the title (e.g. "Date of Publishing") and
> for the Placeholder I'm using an example date to show users the right
> formatting.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/243#issuecomment-192293063>
> .
>



-- 

*Regards,*
*MikdadAli Momin*
*FrontEndDeveloper*

*Sent from my Moto X play*

**Comment by sgomes** [comment]
Ah, that makes sense, thanks @macx! How were you expecting this to be displayed when you first tried it out? Were you expecting the label to be at the top?

**Comment by macx** [comment]
@sgomes I would expect the label at the top. Because it's the same behavior as the users input text.

**Comment by sgomes** [comment]
Yup, that sounds reasonable. Let me take a stab at this and see if it's doable.

**Comment by sgomes** [comment]
@macx I think the best we can do is:
- If you're using a floating label, automatically move it to the top if there's a placeholder. This matches what happens when the user types something.
- If you're not using a floating label, hide it. This also matches what happens when the user types something.

How does that sound?

**Comment by macx** [comment]
@sgomes Sounds perfect!

**Comment by RootCrashed** [comment]
yes


On 4 March 2016 at 20:52, David Maciejewski <notifications@github.com>
wrote:

> @sgomes <https://github.com/sgomes> Sounds perfect!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/material-design-lite/issues/243#issuecomment-192319295>
> .
>



-- 

*Regards,*
*MikdadAli Momin*
*FrontEndDeveloper*

*Sent from my Moto X play*

**Comment by sgomes** [comment]
This is now fixed and released in 1.1.2.

**Comment by JavaGalaxy** [comment]
Hi I am also facing the same issue.
I am using MDB Free 4.2.0. and 1.1.2 version of material design lite.

**Comment by Danbardo** [comment]
This was still a problem for me using 1.3.0.

To fix it I just deleted the labels .mdl-textfield__label on document ready. Seeing as it was only a problem on the login page, it wasn't a big deal.

**Comment by nhducseuit** [comment]
Using 1.3.0 for now.
My guess is this problem was caused by Chrome as this SO question points out
https://stackoverflow.com/questions/35049555/chrome-autofill-autocomplete-no-value-for-password
